name: Build and Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    if: ${{ vars.DEPLOY == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Names
        run: |
          echo "FRONTEND_IMAGE_URL=$(echo ghcr.io/${{ secrets.GH_USER }}/${{ github.event.repository.name }}/${{ secrets.FRONTEND_APP_NAME }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE_URL }}

      - name: Deploy Frontend Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.FRONTEND_APP_NAME }}'
          token: '${{ secrets.FRONTEND_APP_TOKEN }}'
          image: ${{ env.FRONTEND_IMAGE_URL }}
